version: "3"

services:
  th-sensor-reader:
    build: "."
    depends_on:
      - influxdb
    privileged: true
    network_mode: host
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    env_file:
      - ./.env
    restart: unless-stopped

  influxdb:
    image: influxdb:1.8
    volumes:
      - influxdb-storage:/var/lib/influxdb:rw
    env_file:
      - ./.env
    ports:
      - 8086:8086
    restart: unless-stopped
  
  grafana:
    image: grafana/grafana-oss:9.2.1
    volumes:
      - grafana-storage:/var/lib/grafana
    links:
      - influxdb:influxdb
    ports:
      - 3000:3000
    env_file:
      - ./.env
    restart: unless-stopped

volumes:
  influxdb-storage:
  grafana-storage:
